baseURL = 'https://luizera.com.br/'
languageCode = 'en-us'
title = 'Luizera´s quotes'
theme = 'luizera_theme'
copyright = 'All Rights Reserved'
[params.author]
    name = "Luiz Henrique"
    description = "Programador Flutter e aspirante à barman da galera. Faço uns desenhos e uns drinks malucos. Just 4fun"
    email = "luiz.hgsilva@hotmail.com"
    github = "https://github.com/silva-luiz/"