baseURL = 'https://luizera.com.br/'
languageCode = 'en-us'
title = 'Drinks & bytes'
theme = 'luizera_theme'
copyright = 'All Rights Reserved'
[author]
    name = "Luizera"
    description = "Estudante de análise e desenvolvimento de sistemas, programador Flutter, apaixonado por filmes e aspirante à barman da galera. Faço uns desenhos e uns drinks malucos"
    email = "luiz.hgsilva@hotmail.com"
    github = "https://github.com/silva-luiz/"