contentDir = 'content/en'
languageCode = 'en-US'
languageName = 'EN'
weight = 1

title = 'Luizera´s quotes'
copyright = 'All Rights Reserved'

[author]
    name = "Luizera"
    description = "Programador Flutter e aspirante à barman da galera. Faço uns desenhos e uns drinks malucos"
    email = "luiz.hgsilva@hotmail.com"
    github = "https://github.com/silva-luiz/"